name: test_news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  scrollable_positioned_list: ^0.3.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  auto_route: ^9.2.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/strings/
    - assets/images/